name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: HeroTest.testSleep
      id: herotest-testsleep
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testSleep
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testSleep"
        timeout: 10
        max-score: 3
    - name: HeroTest.testSit
      id: herotest-testsit
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testSit
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testSit"
        timeout: 10
        max-score: 3
    - name: HeroTest.testSlip
      id: herotest-testslip
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testSlip
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testSlip"
        timeout: 10
        max-score: 3
    - name: HeroTest.testRun
      id: herotest-testrun
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: HeroTest.testRun
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "HeroTest.testRun"
        timeout: 10
        max-score: 3
    - name: testMain
      id: testmain
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: testMain
        setup-command: ''
        command: sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog71Test.testMain"
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HEROTEST-TESTSLEEP_RESULTS: "${{steps.herotest-testsleep.outputs.result}}"
        HEROTEST-TESTSIT_RESULTS: "${{steps.herotest-testsit.outputs.result}}"
        HEROTEST-TESTSLIP_RESULTS: "${{steps.herotest-testslip.outputs.result}}"
        HEROTEST-TESTRUN_RESULTS: "${{steps.herotest-testrun.outputs.result}}"
        TESTMAIN_RESULTS: "${{steps.testmain.outputs.result}}"
      with:
        runners: herotest-testsleep,herotest-testsit,herotest-testslip,herotest-testrun,testmain
